name: Daily Yarn Start

on:
  schedule:
    - cron: "1,10 4 * * 2,3,4,5,6,0"
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Init real-url
        run: git submodule update --init --recursive
        
      - name: Update real-url
        run: git submodule update --recursive --remote

      - name: Install dependencies
        run: pip3 install -r ./real_url/requirements.txt

      - name: Start app
        run: python3 ./index.py

      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: bot
          author_email: bot@github.com
          message: "[Auto-commit] ${{ github.event_name }} #${{ github.run_number }} at ${{ env.CURRENT_DATETIME }}"
