name: Daily Yarn Start

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  start:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Update dependencies
        run: yarn upgrade lsar --latest

      - name: Install dependencies
        run: yarn install

      - name: Start app
        run: yarn start

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: test
          author_email: test@example.com
          message: "Auto-commit changes on ${{ github.event_name }} #$RUN_NUMBER at $(date +'%Y-%m-%d %H:%M:%S')"
